plugin/model_part.py
tests/test_model_part.py

needed for creating the meshes / modelparts in salome, as Kratos is not available inside of salome
(also using the py-interface of ModelPart is slow for large problems)

Step 1 implementing py-ModelPart

---

plugin/connectivities_io.py
plugin/geometries_io.py
plugin/mesh_interface.py
plugin/model_part.py
plugin/module_reload_order.py
plugin/utilities/salome_utilities.py
plugin/utilities/utils.py
plugin/write_mdpa.py
tests/execute_in_salome.py
tests/test_geometries_io.py
tests/test_mesh_interface.py
tests/test_model_part.py
tests/test_salome_utilities.py

This is the last main step in the backend.
With this one will also be able to create ModelParts by hand (examples for this will follow, it is basically what I do in the tests)

Adding Geometries IO

---

plugin/write_mdpa.py
tests/test_write_mdpa.py

Otherwise this will always show up in the CI as changed

making the writting of the creation time optional

---

.github/CODEOWNERS

for now I am the only owner, but this is likely to be changed in the future, esp after this is moved to the Kratos-Repo

adding init version of CODEWONERS

---

.github/workflows/ci.yml

needed until this is implemented by Github

adding canceling of redundant builds

---

create_kratos_input_tui.py
ks_plugin/plugin_logging.py
tests/initialize_testing_environment.py
tests/run_all_tests.py
tests/test_create_kratos_input_tui.py
tests/test_geometries_io.py
tests/test_mesh_interface.py
tests/test_model_part.py
tests/test_salome_utilities.py
tests/test_utils.py
tests/test_write_mdpa.py
tests/testing_utilities.py

also contains major improvements for the testing environment, now it finally works properly (including no logging during testing!)

Test create kratos input tui, Part I

---

create_kratos_input_tui.py
documentation/README.md
documentation/user_guide.md
kratos_salome_plugin/plugin_logging.py

now also exceptions are being logged
TODO: check if this also works properly with the GUI

Log exceptions

---

kratos_salome_plugin/model_part.py
tests/mdpa_ref_files/ref_conditions.mdpa
tests/mdpa_ref_files/ref_elements.mdpa
tests/test_check_model_part_hierarchie.py
tests/test_model_part.py
tests/test_write_mdpa.py
tests/testing_utilities.py

Compare modelpart & CheckModelPartHierarchie

---

kratos_salome_plugin/gui/project_path_handler.py
kratos_salome_plugin/module_reload_order.py
tests/test_project_path_handler.py

very first PR towards GUI, this small utility class interacts with the user with file dialogs for opening/saving projects

adding project-path-handler

---

kratos_salome_plugin/gui/plugin_controller.py
kratos_salome_plugin/gui/plugin_main_window.py
kratos_salome_plugin/gui/ui_forms/plugin_main_window.ui

missing: centering properly the layout, seems to not be straight forward

App button

---

create_kratos_input_tui.py
kratos_salome_plugin/mesh_interface.py
kratos_salome_plugin/reload_modules.py
kratos_salome_plugin/salome_mesh_utilities.py
kratos_salome_plugin/salome_utilities.py
tests/test_plugin_main_window.py
tests/test_salome_mesh_utilities.py
tests/test_salome_study_utilities.py
tests/test_salome_utilities.py

further splitting the utilities

Salome mesh utilities

---

.github/assert_run_in_salome.py
kratos_salome_plugin/__init__.py
kratos_salome_plugin/plugin_logging.py
kratos_salome_plugin/utilities.py
tests/initialize_testing_environment.py
tests/test_project_manager.py
tests/test_salome_plugins.py
tests/testing_utilities.py

now is checked when importing the plugin, avoids nasty problems with uninitialized salome

Check salome initialization

---

kratos_salome_plugin/base_application.py
kratos_salome_plugin/gui/project_manager.py
kratos_salome_plugin/salome_study_utilities.py
tests/initialize_testing_environment.py
tests/test_project_manager.py
tests/test_salome_study_utilities.py
tests/test_utilities.py
tests/testing_utilities.py

this stil needs some more tests (e.g. for exceptions and logs) but anyway the functionalities for the groups and the apps are missing so the other tests will be added when the missing things are being implemented

ProjectManager using pathlib

---

kratos_salome_plugin/gui/plugin_controller.py

TODO check if this also works in Win

fix main window visibility

---

kratos_salome_plugin/plugin_logging.py
salome_plugins.py

for the future when things will be configurable

adding notes for which things should be made configurable

---

.github/docker_ubuntu_bionic/DockerFile
.github/workflows/check_salome_execution.yml
.github/workflows/ci.yml
.github/workflows/dockerimage.yml
kratos_salome_plugin/__init__.py
kratos_salome_plugin/version.py
salome_plugins.py
tests/aux_files/excepthook_test.py

Salome 9.5 was released yesterday:
https://www.salome-platform.org/news/28-jul-2020-salome-version-9.5.0

[CI] adding Salome 9.5

---

README.md

extend description in readme

---

kratos_salome_plugin/gui/plugin_controller.py
kratos_salome_plugin/gui/plugin_main_window.py
tests/test_plugin_controller.py
tests/test_plugin_main_window.py

this fixes the window not showing up again after minimizing on Windows

fix minimizing issue

---

kratos_salome_plugin/gui/plugin_main_window.py
tests/test_plugin_main_window.py

adding basic printing capabilities to the statusbar of the main window

[GUI] MainWindow add StatusBar functionalities

---

kratos_salome_plugin/gui/project_manager.py
tests/test_project_manager.py

Still test for the logging could be added

PluginManager adding more tests

---

kratos_salome_plugin/gui/plugin_main_window.py

[GUI] main window: hide instead close

---

development/test_weakref.py
kratos_salome_plugin/geometries_io.py
kratos_salome_plugin/gui/plugin_controller.py
kratos_salome_plugin/gui/project_manager.py
kratos_salome_plugin/gui/project_path_handler.py
kratos_salome_plugin/mesh_interface.py
kratos_salome_plugin/model_part.py
tests/test_check_model_part_hierarchie.py
tests/test_geometries_io.py
tests/test_model_part.py
tests/testing_utilities.py

remove object inheritance

---

kratos_salome_plugin/mesh_interface.py

This is a minor refactor (also removes the double definition of `GetNodes`)

[MeshInterface] using lambdas

---

kratos_salome_plugin/geometries_io.py

[GeomIO] using dict for switch

---

kratos_salome_plugin/reload_modules.py
kratos_salome_plugin/salome_gui_utilities.py
tests/initialize_testing_environment.py
tests/test_salome_gui_utilities.py

Adding utilities to interact with the Salome GUI

Adding Salome GUI utilities

---

kratos_salome_plugin/gui/base_window.py
tests/test_base_window.py

some simplification
window becomes the active one if it is shown

[GUI] fix active window

---

kratos_salome_plugin/write_mdpa.py
tests/mdpa_ref_files/ref_create_mdpa_multiple_meshes.mdpa
tests/mdpa_ref_files/ref_create_mdpa_one_mesh.mdpa
tests/mdpa_ref_files/ref_full_model_part.mdpa
tests/mdpa_ref_files/ref_mdpa_header.mdpa

Write mdpa nicer formatting

---

.github/docker_ubuntu_bionic/DockerFile
.github/workflows/check_salome_execution.yml
.github/workflows/ci.yml
.github/workflows/dockerimage.yml

https://files.salome-platform.org/Salome/Salome9.6.0/SALOME_9_6_0_Release_Notes.pdf

[CI] add Salome version 9.6

---

.github/workflows/ci.yml

plus minor updates in CI script

add Python 3.9 in CI

---

README.md
kratos_salome_plugin/gui/plugin_controller.py
kratos_salome_plugin/gui/ui_forms/plugin_main_window.ui
kratos_salome_plugin/plugin_logging.py
tests/test_plugin_controller.py

- after moving repo to KratosMultiphysics
- prepare for using Flowgraph

some updates
